const example_db = [
  {
    key: 1,
    nombre: "Juan",
    apellido: "Pérez",
    cedula: "8-987-1608",
    direccion: "Calle 123, Ciudad XYZ",
    telefono: "123-456-7890",
    centro_de_votacion: "Escuela Primaria ABC",
    mesa: 1,
    activista: "2@activista.com",
    estado_de_votacion: "NO",
  },
  {
    key: 2,
    nombre: "María",
    apellido: "Gómez",
    cedula: "8-968-5",
    direccion: "Avenida Principal, Ciudad WXY",
    telefono: "987-654-3210",
    centro_de_votacion: "Centro Comunitario",
    mesa: 3,
    activista: "2@activista.com",
    estado_de_votacion: "SI",
  },
  {
    key: 3,
    nombre: "Pedro",
    apellido: "Martínez",
    cedula: "E-856-157",
    direccion: "Calle Principal, Ciudad ZYX",
    telefono: "135-792-4680",
    centro_de_votacion: "Biblioteca Pública",
    mesa: 2,
    activista: "1@activista.com",
    estado_de_votacion: "NO",
  },
  {
    key: 4,
    nombre: "Ana",
    apellido: "López",
    cedula: "8-687-1501",
    direccion: "Avenida 456, Ciudad YZX",
    telefono: "246-801-3579",
    centro_de_votacion: "Centro Comunitario",
    mesa: 5,
    activista: "2@activista.com",
    estado_de_votacion: "NO",
  },
  {
    key: 5,
    nombre: "Carlos",
    apellido: "Sánchez",
    cedula: "8-964-1508",
    direccion: "Calle 789, Ciudad XZY",
    telefono: "987-654-3210",
    centro_de_votacion: "Biblioteca Pública",
    mesa: 5,
    activista: "1@activista.com",
    estado_de_votacion: "SI",
  },
  {
    key: 6,
    nombre: "Laura",
    apellido: "Ramírez",
    cedula: "8-954-7810",
    direccion: "Avenida 890, Ciudad ZXY",
    telefono: "567-890-1234",
    centro_de_votacion: "Centro Cívico",
    mesa: 2,
    activista: "1@activista.com",
    estado_de_votacion: "SI",
  },
  {
    key: 7,
    nombre: "Miguel",
    apellido: "González",
    cedula: "8-963-1879",
    direccion: "Calle 234, Ciudad YXZ",
    telefono: "678-901-2345",
    centro_de_votacion: "Universidad Nacional",
    mesa: 2,
    activista: "3@activista.com",
    estado_de_votacion: "NO",
  },
  {
    key: 8,
    nombre: "Sofía",
    apellido: "Díaz",
    cedula: "8-987-1480",
    direccion: "Avenida 567, Ciudad XYZ",
    telefono: "789-012-3456",
    centro_de_votacion: "Centro de Convenciones",
    mesa: 8,
    activista: "3@activista.com",
    estado_de_votacion: "SI",
  },
  {
    key: 9,
    nombre: "Diego",
    apellido: "Hernández",
    cedula: "8-985-1607",
    direccion: "Calle 678, Ciudad ZYX",
    telefono: "890-123-4567",
    centro_de_votacion: "Parque Recreativo",
    mesa: 4,
    activista: "2@activista.com",
    estado_de_votacion: "SI",
  },
  {
    key: 10,
    nombre: "Julia",
    apellido: "Alvarez",
    cedula: "8-457-158",
    direccion: "Avenida 123, Ciudad XZY",
    telefono: "456-789-0123",
    centro_de_votacion: "Parque Recreativo",
    mesa: 8,
    activista: "3@activista.com",
    estado_de_votacion: "NO",
  },
];
export { example_db };
